version: '3.8'

services:
  nginx-registry:
    container_name: nginx-registry
    image: carlonicora/nginx-registry:1.0
    restart: always
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    volumes:
      - ../:/var/www/html:delegated
      - ../logs:/logs/nginx/:delegated
      - ./nginx/hosts:/etc/nginx/sites-available/:delegated
      - ./certbot/conf:/etc/letsencrypt:delegated
      - ./certbot/www:/var/www/certbot:delegated
    networks:
      - default_network
    ports:
      - "80:80"
      - "443:443"
#    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  letsencrypt:
    container_name: letsencrypt
    image: certbot/certbot
    restart: always
    networks:
      - default_network
    volumes:
      - ./certbot/conf:/etc/letsencrypt:delegated
      - ./certbot/www:/var/www/certbot:delegated
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  registry:
    container_name: carlonicora-registry
    image: carlonicora/registry:1.0
    restart: unless-stopped
    working_dir: /var/www/html
    build:
      context: .
      dockerfile: ./php-fpm/Dockerfile
      target: ${ENVIRONMENT}
      args:
        - XDEBUG_HOST=${XDEBUG_HOST}
        - XDEBUG_PORT=${XDEBUG_PORT}
    volumes:
      - ../:/var/www/html:delegated
      - ./nginx/hosts:/etc/nginx/sites-available/:delegated
    networks:
      - default_network

networks:
  default_network:
    driver: bridge
    name: carlonicora
    external: true
